project:
  type: website

website:
  title: "Grafschaft in Zahlen"

  google-analytics:
    tracking-id: "G-GTB3NHRG4V"
    anonymize-ip: true

  cookie-consent:
    type: express
    style: simple
    palette: light
    language: de
    policy-url: datenschutz.html
    prefs-text: "Cookie-Einstellungen"

  navbar:
    logo: images/logo.jpg

    left:
      - href: index.qmd
        text: Start

      - href: news.qmd
        text: Aktuelles

      - href: bevoelkerung.qmd
        text: Bevölkerung

      - href: gesundheit.qmd
        text: Gesundheit

      - href: landwirtschaft.qmd
        text: Landwirtschaft

      - href: about.qmd
        text: Über das Projekt

    tools:
      - icon: instagram
        href: https://www.instagram.com/grafschaftinzahlen/
        aria-label: Grafschaft in Zahlen auf Instagram

  page-footer:
    left:
      - text: "Impressum"
        href: impressum.qmd
      - text: "Datenschutz"
        href: datenschutz.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    lang: de